language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: VszSLcq7oHKJbSsMtoGZupq9BJ5eXiSTfgGyBhvJwaOzL37uRf5miWHXVgxSZwONHtpWUT1AFWRjgnXqvSM5syvWa/xI3Mzfwk8gHzEp6SMu96RoQ9/fyXQIZZcOq98rpSQhWusJymiRw/Vo5M7Y2UbHNvuBqEk+jiF8DIG010U=
  - secure: Ft0LlyXjT5OfhiJvUdnwBSIDKv1Fxg76OHgpYqb+WlDDZsVMI+xchCBVRoXYbKsMc2Xw5/0/dT6OqIf/IyJ4Ikg6li4EllwxWcxOtuiZa2jStDt7zMwyRI2zbczN0CVG5lAT0SHdQ+Hhy5RWdLWSwJcuOUM1QojiriRFv6xLykA=
